### ISSUE TITLE
Routing issue in `dfrbp_1` flop

### ISSUE THREAD

**Issue by sergeiandreyev** [IHP-GmbH/IHP-Open-PDK#166]
## Environment

- Klayout Version: 0.29.2
- OS/Platform: Linux

## Expected Behavior
One should be able to connect CLK pin in `dfrbp_1` stdcell flop with M2

## Actual Behavior
DRC violation when the Via is put because of too small distance between Reset M2 bar and CLK pin

## Steps to Reproduce the Problem

1. Try to put min Via on CLK pin
2. Run DRC
3. It will produce violation

**Comment by KrzysztofHerman** [comment]
@sergeiandreyev in order to make a valid contact one have to put the via and metal2 on the limit of the technology (see DRC rules `M2.b` and `Via1.c`). 
![image](https://github.com/user-attachments/assets/a9cf57fc-b181-43f2-b638-67343a860be1)

The tools like OpenROAD already deal with it without any issues.

![image](https://github.com/user-attachments/assets/4787ff70-01f0-4247-ad73-8a809c099754)

**Comment by sergeiandreyev** [comment]
the issue relates to commercial PDK flow
