### ISSUE TITLE
PCELL for npn13G2 seems broken

### ISSUE THREAD

**Issue by olisnr** [IHP-GmbH/IHP-Open-PDK#286]
Environment
dev & main branch LVS scripts KLayout 0.29.8 linuX

Expected Behavior
the PCELL should generate a **npn13G2** like in the example of 
`ihp-sg13g2/libs.ref/sg13g2_pr/gds/sg13g2_pr.gds
`
Actual Be (bottom left)
![PCELL](https://github.com/user-attachments/assets/84de880b-4b5e-4a39-be8b-361980819ff3)
havior

Steps to Reproduce the Problem
place a npn13G2 from SG13_dev or main ...

**Comment by KrzysztofHerman** [comment]
@olisnr 
It works but unfortunately you have to generate it in two steps. It is not documented so our bad. 
In general, in order to generate npn13G2 device you have to do it executing a particular sequence. 

1. Drag and drop a `npn13G2_base` device
2. Drag and drop a `npn13G2` device
3. Remove `npn13G2_base` device
4. Edit your cell.
5. If you need you can add more `npn13G2` devices

**Comment by sergeiandreyev** [comment]
Hi @olisnr, can we close this one or is there anything else we can do for this issue? btw, I'm considering aligning different ways of instantiation between the `npn13G2*` devices, but it is not of a highest priority right now

**Comment by olisnr** [comment]
somewhere it should be explained.
