### ISSUE TITLE
LF-noise npn13g2

### ISSUE THREAD

**Issue by dwarning** [IHP-GmbH/IHP-Open-PDK#43]
I try to reproduce the LF noise results from document Low_Frequency_Noise_SG13G2.pdf, page 3 with latest ngspice and IHP-Open-PDK.

My setup (see attachment) is as follows: Using an 8 emitter stripe (NX=8) as DUT, biasing the base over bias T with DC (0.7...0.9V) and AC voltage sources, DC Vce=1V on collector, grep the power spectral density of ic with a H controlled source and divided by Beta² 

The result has a large difference to the shown diagram on p.3

![Bildschirmfoto vom 2024-02-07 13-53-42](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/18441932/b13753ba-6bf7-4014-a810-4d5afa006fba)

[vbic_noise_Vc_Vb.sp.txt](https://github.com/IHP-GmbH/IHP-Open-PDK/files/14194134/vbic_noise_Vc_Vb.sp.txt)

Is there a flaw in my method or did we have a problem with the model in ngspice? Can you describe your method in principle, please. Which simulator you have used for the documentation?

**Comment by metroid120** [comment]
Hi dwarning,

I went through the relevant literature and compared it to your circuit. I recommend to have a look at :
- https://www.iee.et.tu-dresden.de/iee/eb/forsch/AK-Bipo/2000/AKB_2000_Berkner_1f_noise.pdf
- in the ICCAP modeling handbook, the chapter "Low Noise Measurements and Modeling"

After comparing the circuits given in these references to yours, I noticed that you did not connect V1 as a 
"dummy", which is needed so that spice can simulate noise. V1 should, in my opinion, not be connected to 
the transistor at all. 

Attached are my circuit and results, what do you think? In my opinion, this looks decent.

![Screenshot_select-area_20240208180506](https://github.com/IHP-GmbH/IHP-Open-PDK/assets/57661320/eeca6500-15dd-40ff-852c-5f3ed82a8962)


[vbic_noise_Vc_Vb.sp.txt](https://github.com/IHP-GmbH/IHP-Open-PDK/files/14212383/vbic_noise_Vc_Vb.sp.txt)

**Comment by dwarning** [comment]
@metroid120:
Yes, the reference voltage source can't connect to base. With this connection noise of the base resistor are not taken in account.
Thank you for this correction and the reference paper.
So the results are in line with the pdk document.
